### ISSUE TITLE
retrieving id of document

### ISSUE THREAD

**Issue by rfb** [premshree/use-pagination-firestore#2]
Hi! Great library! Do you have any suggestions for retrieving the ID for the document? 

If you could exposed `docs` from the state, we could handle the `QueryDocumentSnapshot`'s directly and retrieve the IDs?

**Comment by premshree** [comment]
Hi @rfb, thank you for your feedfback! What do you think about if I exposed the `id` of each document with the `items`, so that you could do something like this:

```ts
 const { items, isLoading, isStart, isEnd, getPrev, getNext } = usePagination<SomeDocumentType>(
    firebase.firestore().collection('/collection').orderBy('updated', 'desc'),
    {
      limit: 10,
    },
  );
```

This will make `items` of type `(T & Pick<DocumentSnapshot<SomeDocumentType>, "id">)[]` so each item will have the document's `id` property along with it. I think this will keep the API simple and also provide the `id` of the document which seems like a reasonable property to want to expose. LMK what you think!

**Comment by MorenoMdz** [comment]
Hey there, joining the conversation, what I did is add the id by hand to the lib, but would be best to have it as default. Ï

![image](https://user-images.githubusercontent.com/29472480/113604098-2db43400-961b-11eb-9f04-200d150609fb.png)

Is there a use case where having the ID is not ideal? If so, we can have a tag at the second param object like `useId`, if you want I can make a PR for that.

Thanks for the lib.

**Comment by rfb** [comment]
Thanks for the quick reply @premshree and @MorenoMdz 

Adding the ID is good and I agree with @MorenoMdz - it is important that the key for the id was added as a parameter. react-firebase-hooks does something similar with [useCollectionData](https://github.com/csfrequency/react-firebase-hooks/tree/aeadd15b3f8ca642f52776edf2e4dad62a00d449/firestore#usecollectiondata). The `options` has an `idField` attribute.

Another thought: a reference to the document is still important in some situations. Again, looking at react-firebase-hooks, they have defined two methods for retrieving a collection, [useCollectionData](https://github.com/csfrequency/react-firebase-hooks/tree/aeadd15b3f8ca642f52776edf2e4dad62a00d449/firestore#usecollectiondata) and [useCollection](https://github.com/csfrequency/react-firebase-hooks/tree/aeadd15b3f8ca642f52776edf2e4dad62a00d449/firestore#usecollection). The first returns an array of document data, the second returns document references.

In my case, I need the reference to resolve documents relative to the documents returned by `usePaginationFirestore`

**Comment by MorenoMdz** [comment]
Hey, I am joining the conversation as I found this lib while searching for pagination options for Firestore, in my case having the document ID is essential, as we use it for many other 

> Thanks for the quick reply @premshree and @MorenoMdz
> 
> Adding the ID is good and I agree with @MorenoMdz - it is important that the key for the id was added as a parameter. react-firebase-hooks does something similar with [useCollectionData](https://github.com/csfrequency/react-firebase-hooks/tree/aeadd15b3f8ca642f52776edf2e4dad62a00d449/firestore#usecollectiondata). The `options` has an `idField` attribute.
> 
> Another thought: a reference to the document is still important in some situations. Again, looking at react-firebase-hooks, they have defined two methods for retrieving a collection, [useCollectionData](https://github.com/csfrequency/react-firebase-hooks/tree/aeadd15b3f8ca642f52776edf2e4dad62a00d449/firestore#usecollectiondata) and [useCollection](https://github.com/csfrequency/react-firebase-hooks/tree/aeadd15b3f8ca642f52776edf2e4dad62a00d449/firestore#usecollection). The first returns an array of document data, the second returns document references.
> 
> In my case, I need the reference to resolve documents relative to the documents returned by `usePaginationFirestore`

It does make sense, but can't you actually reference it by Id? In the end, does it really matter for the SDK if you are using the ref itself or a new query with the document id?

**Comment by premshree** [comment]
@rfb @MorenoMdz I have a PR here: https://github.com/premshree/use-pagination-firestore/pull/3

LMK what y'all think, and I can push up a new package!

**Comment by MorenoMdz** [comment]
> @rfb @MorenoMdz I have a PR here: #3 – it also exposes the raw documents via `docs`, which seems fine as nothing is lost providing that.
> 
> LMK what y'all think, and I can push up a new package!

Fast, nice.

It should not really matter perf wise but it could be optional to return the document ref array, as it is in a way redundant to return both. For now, that works for me, it should do what @rfb needs as well.

**Comment by premshree** [comment]
@MorenoMdz yeah, agreed, it shouldn't really matter perf-wise since `items` is constructed from `docs` anyway – there might be some implication with memory for very large collections, but happy to defer that for later if that becomes an issue!

**Comment by MorenoMdz** [comment]
> @MorenoMdz yeah, agreed, it shouldn't really matter perf-wise since `items` is constructed from `docs` anyway – there might be some implication with memory for very large collections, but happy to defer that for later if that becomes an issue!

Going offtopic, do you intend to ad page navigation support somehow? It is a bit painful as we don't have a query count from Firestore, but it's something very nice to have.

**Comment by premshree** [comment]
@MorenoMdz @rfb I just published `use-pagination-firestore-0.4.0` – LMK if you run into issues specific to the `id` field.

**Comment by MorenoMdz** [comment]
It worked here, thanks for the quick update!

**Comment by premshree** [comment]
Closing this issue as resolved.

**Comment by rfb** [comment]
Thanks @premshree !
