### ISSUE TITLE
is there any way I can do refetch of this hook similar to userQuery of react query.

### ISSUE THREAD

**Issue by Shashi-GS** [premshree/use-pagination-firestore#6]
Hi,

This is really useful library. is there any way I can do refetch the data on click of a button?
I am trying to do a search on click of a button with pagination.

--
Thanks in Advance,
Shashi

**Comment by premshree** [comment]
> Hi,
> 
> This is really useful library. is there any way I can do refetch the data on click of a button?
> I am trying to do a search on click of a button with pagination.
> 
> --
> Thanks in Advance,
> Shashi

Hi @Shashi-GS 

You can initialize the query as `undefined` and then use a callback to dynamically set the query when user clicks the search button. @matziol added this ability [recently](https://github.com/premshree/use-pagination-firestore/pull/5/files). LMK if this works for you!

**Comment by premshree** [comment]
Closing this. Please let me know if you have more questions!
